CREATE DATABASE QuanLyBanHang2;
USE QuanLyBanHang2;

-- DROP DATABASE QuanLyBanHang2;

-- 1. Bảng KHACHHANG
CREATE TABLE KhachHang(
	MaKH CHAR(4) PRIMARY KEY,
    TenKH VARCHAR(30) NOT NULL,
    DiaChi VARCHAR(50),
    NgaySinh DATE,
    Phone VARCHAR(15) UNIQUE
);

-- 2. Bảng NHANVIEN
CREATE TABLE NhanVien(
	MaNV CHAR(4) PRIMARY KEY,
    Ten VARCHAR(30) NOT NULL,
    GioiTinh BIT NOT NULL,
    DiaChi VARCHAR(50) NOT NULL,
    NgaySinh DATE NOT NULL,
    Phone VARCHAR(15) UNIQUE,
    Email TEXT,
    NoiSinh VARCHAR(20) NOT NULL,
    NgayVaoLam DATE,
    MaNQL CHAR(4)
);

-- 3. Bảng NHACUNGCAP
CREATE TABLE NhaCC(
	MaNCC CHAR(5) PRIMARY KEY,
    TenNCC VARCHAR(50) NOT NULL,
    DiaChiNCC VARCHAR(50) NOT NULL,
    Phone VARCHAR(15) NOT NULL,
    Email VARCHAR(30) NOT NULL,
    Website VARCHAR(30)
);

-- 4. Bảng LOAISP
CREATE TABLE LoaiSP(
	MaLSP CHAR(4) PRIMARY KEY,
    TenLSP VARCHAR(30) NOT NULL,
    GhiChu TEXT NOT NULL
);

-- 5. Bảng SANPHAM
CREATE TABLE SanPham(
	MaSP CHAR(4) PRIMARY KEY,
    TenSP VARCHAR(50) NOT NULL,
    DonViTinh VARCHAR(10) NOT NULL,
    GhiChu TEXT,
    MaLSP CHAR(4) NOT NULL,
    FOREIGN KEY (MaLSP)REFERENCES LoaiSP(MaLSP)
);

-- 6. Bảng PHIEUNHAP
CREATE TABLE PhieuNhap(
	SoPN CHAR(5) PRIMARY KEY,
    NgayNhap DATE NOT NULL DEFAULT(NOW()),
    GhiChu TEXT,
    MaNCC CHAR(5) NOT NULL,
    MaNV CHAR(4) NOT NULL,
    FOREIGN KEY (MaNCC) REFERENCES NhaCC (MaNCC),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

-- 7. Bảng CTPHIEUNHAP
CREATE TABLE CTPhieuNhap(
	MaSP CHAR(4) NOT NULL,
    SoPN CHAR(5) NOT NULL,
    FOREIGN KEY (MaSP) REFERENCES SanPham (MaSP),
    FOREIGN KEY (SoPN) REFERENCES PhieuNhap (SoPN),
    PRIMARY KEY(MaSP,SoPN),
    SoLuong SMALLINT NOT NULL DEFAULT (0),
    GiaNhap REAL NOT NULL CHECK (GiaNhap >=0)
);

-- 8. Bảng PHIEUXUAT
CREATE TABLE PhieuXuat(
	SoPX CHAR(5) PRIMARY KEY,
	MaNV CHAR(4) NOT NULL,
    MaKH CHAR(4) NOT NULL,
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    NgayBan DATE NOT NULL,
    GhiChu TEXT
);

-- 9. Bảng CTPHIEUXUAT
CREATE TABLE CTPhieuXuat(
	SoPX CHAR(5),
    MaSP CHAR(4),
    SoLuong SMALLINT CHECK (SoLuong>0),
    GiaBan REAL  CHECK (GiaBan >0),
	FOREIGN KEY (SoPX) REFERENCES PhieuXuat (SoPX),
    FOREIGN KEY (MaSP) REFERENCES SanPham (MaSP),
    PRIMARY KEY (SoPX,MaSP)
);

-- 1. Thêm 2 Phiếu nhập trong tháng hiện hành.
INSERT INTO PhieuNhap (SoPN,NgayNhap,GhiChu,MaNCC,MaNV)VALUES ()










